;;; bible-normalize-input.el ---  -*- lexical-binding: t; -*-

(provide 'bible-normalize-input)

(require 'bible-canonical-book-list)

(defconst bible--book-aliases-raw
  '((("Genesis" "Gen" "Gn") . "Genesis")
    (("Exodus" "Exod" "Ex") . "Exodus")
    (("Leviticus" "Lev" "Lv") . "Leviticus")
    (("Numbers" "Num" "Nm" "Numeri") . "Numbers")
    (("Deuteronomy" "Deut" "Dt" "Deuteronomium") . "Deuteronomy")
    (("Joshua" "Josh" "Jos" "Josue") . "Joshua")
    (("Judges" "Judg" "Jdg" "Judicum") . "Judges")
    (("Ruth" "Ru") . "Ruth")
    (("1 Samuel" "1 Sam" "1 Sm" "1 Kingdoms" "1 Kgdms" "Regum I") . "1 Samuel")
    (("2 Samuel" "2 Sam" "2 Sm" "2 Kingdoms" "2 Kgdms" "Regum II") . "2 Samuel")
    (("1 Kings" "1 Kgs" "1 Ki" "3 Kingdoms" "3 Kgdms" "Regum III") . "1 Kings")
    (("2 Kings" "2 Kgs" "2 Ki" "4 Kingdoms" "4 Kgdms" "Regum IV") . "2 Kings")
    (("1 Chronicles" "1 Chron" "1 Chr" "1 Paralipomena" "Paralipomenon I" "1 Paralipomenon") . "1 Chronicles")
    (("2 Chronicles" "2 Chron" "2 Chr" "2 Paralipomena" "Paralipomenon II" "2 Paralipomenon") . "2 Chronicles")
    (("Ezra" "Esdras" "1 Esdras" "Esdræ") . "Ezra")
    (("Nehemiah" "Neh" "2 Esdras" "Nehemiæ") . "Nehemiah")
    (("Tobit" "Tobias" "Tob" "Tobiæ") . "Tobit")
    (("Judith" "Jdt") . "Judith")
    (("Esther" "Est") . "Esther")
    (("1 Maccabees" "1 Mac" "1 Machabees" "Machabæorum I") . "1 Maccabees")
    (("2 Maccabees" "2 Mac" "2 Machabees" "Machabæorum II") . "2 Maccabees")
    (("Job") . "Job")
    (("Psalms" "Psalm" "Ps" "Psalmi") . "Psalms")
    (("Proverbs" "Prov" "Prv") . "Proverbs")
    (("Ecclesiastes" "Eccl" "Qoheleth") . "Ecclesiastes")
    (("Song of Songs" "Song" "Sg" "Canticle of Canticles" "Canticum Canticorum" "Canticles") . "Song of Songs")
    (("Wisdom" "Wis" "Sapientia") . "Wisdom")
    (("Sirach" "Sir" "Ecclesiasticus") . "Sirach")
    (("Isaiah" "Is" "Isaias") . "Isaiah")
    (("Jeremiah" "Jer" "Jeremias") . "Jeremiah")
    (("Lamentations" "Lam" "Lamentationes") . "Lamentations")
    (("Baruch" "Bar") . "Baruch")
    (("Ezekiel" "Ezek" "Eze" "Ezechiel") . "Ezekiel")
    (("Daniel" "Dan" "Dn") . "Daniel")
    (("Hosea" "Hos" "Osee") . "Hosea")
    (("Joel" "Jl") . "Joel")
    (("Amos" "Am") . "Amos")
    (("Obadiah" "Obad" "Obdias" "Abdias") . "Obadiah")
    (("Jonah" "Jon" "Jonas") . "Jonah")
    (("Micah" "Mic" "Michaeas" "Michæa" "Micheas") . "Micah")
    (("Nahum" "Na") . "Nahum")
    (("Habakkuk" "Hab" "Habacuc") . "Habakkuk")
    (("Zephaniah" "Zeph" "Sophonias") . "Zephaniah")
    (("Haggai" "Hag" "Aggaeus" "Aggæus" "Aggeus") . "Haggai")
    (("Zechariah" "Zech" "Zacharias") . "Zechariah")
    (("Malachi" "Mal" "Malachias") . "Malachi")
    (("Matthew" "Matt" "Mt" "Matthæum") . "Matthew")
    (("Mark" "Mk" "Marcum") . "Mark")
    (("Luke" "Lk" "Lucam") . "Luke")
    (("John" "Jn" "Joannem") . "John")
    (("Acts" "Acts of Apostles" "Act" "Ac" "Actus Apostolorum") . "Acts")
    (("Romans" "Rom" "Romanos") . "Romans")
    (("1 Corinthians" "1 Cor" "1 Corinthios") . "1 Corinthians")
    (("2 Corinthians" "2 Cor" "2 Corinthios") . "2 Corinthians")
    (("Galatians" "Gal" "Galatas") . "Galatians")
    (("Ephesians" "Eph" "Ephesios") . "Ephesians")
    (("Philippians" "Phil" "Phl" "Php" "Philippenses") . "Philippians")
    (("Colossians" "Col" "Colossenses") . "Colossians")
    (("1 Thessalonians" "1 Thess" "1 Thes" "1 Thessalonicenses") . "1 Thessalonians")
    (("2 Thessalonians" "2 Thess" "2 Thes" "2 Thessalonicenses") . "2 Thessalonians")
    (("1 Timothy" "1 Tim" "1 Tm" "1 Timotheum") . "1 Timothy")
    (("2 Timothy" "2 Tim" "2 Tm" "2 Timotheum") . "2 Timothy")
    (("Titus" "Tit") . "Titus")
    (("Philemon" "Phlm" "Philemonem") . "Philemon")
    (("Hebrews" "Heb" "Hebræos") . "Hebrews")
    (("James" "Jas" "Jacobi") . "James")
    (("1 Peter" "1 Pet" "1 Pt" "1 Petri") . "1 Peter")
    (("2 Peter" "2 Pet" "2 Pt" "2 Petri") . "2 Peter")
    (("1 John" "1 Jn" "1 Joannis") . "1 John")
    (("2 John" "2 Jn" "2 Joannis") . "2 John")
    (("3 John" "3 Jn" "3 Joannis") . "3 John")
    (("Jude" "Jud" "Judæ") . "Jude")
    (("Revelation" "Rev" "Apocalypse" "Apoc" "Apocalypsis") . "Revelation"))
  "Mapping of input names to canonical names")

(defvar bible--book-alias-table
  (let ((table (make-hash-table :test #'equal)))
    (dolist (entry bible--book-aliases-raw)
      (let ((aliases (car entry))
            (canonical (cdr entry)))
        (dolist (alias aliases)
          (puthash (downcase alias) canonical table))))
    table)
  "Hash table mapping lowercased aliases to canonical book names.")

(defun bible--canonical-book-name (input)
  "Return canonical book name from INPUT, or signal an error."
  (let ((key (downcase input)))
    (or (gethash key bible--book-alias-table)
        (error "Unknown book name: %s" input))))



(defconst bible--translation-aliases
  '(("knox"         . "knox")
    ("knox bible"   . "knox")
    ("knx"          . "knox")
    ("vulgate"      . "vulgate")
    ("douay rheims" . "douay_rheims")
    ("douay_rheims" . "douay_rheims")
    ("drb"          . "douay_rheims")
    ("douay"        . "douay_rheims")
    ("douay-rheims" . "douay_rheims")
    ("d-r"          . "douay_rheims")
    ("esv"          . "esv"))
  "Mapping of lowercase translation aliases to canonical internal translation names.")

(defun bible--normalize-translation (name)
  "Return canonical translation name for NAME (e.g., 'drb' → 'douay_rheims').
Raises error if unknown."
  (let* ((key (downcase name))
         (norm (assoc-default key bible--translation-aliases #'string=)))
    (or norm (error "Unknown translation: %s" name))))
