;;; bible-books.el --- Bible book name mappings for different translations

;; Provides normalized lookup tables mapping canonical names to URL paths
;; for the Knox, Douay-Rheims, and Vulgate translations.

;; These are for retrieving and Bible verses from
;; https://catholicbible.online for multiple translations.

(provide 'catholicbible-books)

(defconst catholicbible--knox-books
  '(;; --- Old Testament ---
    ("genesis"        . "/OT/Gen")   ("gen"         . "/OT/Gen")
    ("exodus"         . "/OT/Ex")    ("ex"          . "/OT/Ex")
    ("leviticus"      . "/OT/Lev")   ("lev"         . "/OT/Lev")
    ("numbers"        . "/OT/Num")   ("num"         . "/OT/Num")
    ("deuteronomy"    . "/OT/Dt")    ("deut"        . "/OT/Dt")
    ("josue"          . "/OT/Jos")   ("joshua"      . "/OT/Jos")
    ("judges"         . "/OT/Judg")  ("judg"        . "/OT/Judg")
    ("ruth"           . "/OT/Ru")
    ("1 kings"        . "/OT/1_Kgs") ("i kings"     . "/OT/1_Kgs")
    ("2 kings"        . "/OT/2_Kgs") ("ii kings"    . "/OT/2_Kgs")
    ("3 kings"        . "/OT/3_Kgs") ("iii kings"   . "/OT/3_Kgs")
    ("4 kings"        . "/OT/4_Kgs") ("iv kings"    . "/OT/4_Kgs")
    ("1 paralipomena" . "/OT/1_Par") ("i paralipomena" . "/OT/1_Par")
    ("2 paralipomena" . "/OT/2_Par") ("ii paralipomena" . "/OT/2_Par")
    ("1 esdras"       . "/OT/Esd")   ("esdras"      . "/OT/Esd")
    ("2 esdras"       . "/OT/Neh")   ("nehemiah"    . "/OT/Neh")
    ("tobias"         . "/OT/Tob")   ("tobit"       . "/OT/Tob")
    ("judith"         . "/OT/Jdt")
    ("esther"         . "/OT/Est")
    ("job"            . "/OT/Job")
    ("psalms"         . "/OT/Ps")    ("ps"          . "/OT/Ps")
    ("proverbs"       . "/OT/Prov")
    ("ecclesiastes"   . "/OT/Eccl")
    ("song of songs"  . "/OT/Cant")  ("canticle"    . "/OT/Cant")
    ("wisdom"         . "/OT/Wis")
    ("ecclesiasticus" . "/OT/Eccle") ("sirach"      . "/OT/Eccle")
    ("isaias"         . "/OT/Isa")   ("isaiah"      . "/OT/Isa")
    ("jeremias"       . "/OT/Jer")   ("jeremiah"    . "/OT/Jer")
    ("lamentations"   . "/OT/Lam")
    ("baruch"         . "/OT/Bar")
    ("ezechiel"       . "/OT/Eze")   ("ezekiel"     . "/OT/Eze")
    ("daniel"         . "/OT/Dan")
    ("osee"           . "/OT/Os")    ("hosea"       . "/OT/Os")
    ("joel"           . "/OT/Jo")
    ("amos"           . "/OT/Am")
    ("abdias"         . "/OT/Abd")   ("obadiah"     . "/OT/Abd")
    ("jonas"          . "/OT/Jon")   ("jonah"       . "/OT/Jon")
    ("michaeas"       . "/OT/Mic")   ("micah"       . "/OT/Mic")
    ("nahum"          . "/OT/Nah")
    ("habacuc"        . "/OT/Hab")   ("habakkuk"    . "/OT/Hab")
    ("sophonias"      . "/OT/Sop")   ("zephaniah"   . "/OT/Sop")
    ("aggaeus"        . "/OT/Agg")   ("haggai"      . "/OT/Agg")
    ("zacharias"      . "/OT/Zac")   ("zechariah"   . "/OT/Zac")
    ("malachias"      . "/OT/Mal")   ("malachi"     . "/OT/Mal")
    ("1 machabees"    . "/OT/1_Mac") ("i machabees" . "/OT/1_Mac")
    ("2 machabees"    . "/OT/2_Mac") ("ii machabees". "/OT/2_Mac")

    ;; --- New Testament ---
    ("matthew"        . "/NT/Mat")
    ("mark"           . "/NT/Mk")
    ("luke"           . "/NT/Lk")
    ("john"           . "/NT/Jn")
    ("acts"           . "/NT/Act")   ("acts of apostles" . "/NT/Act")
    ("romans"         . "/NT/Rom")
    ("1 corinthians"  . "/NT/1_Cor") ("i corinthians" . "/NT/1_Cor")
    ("2 corinthians"  . "/NT/2_Cor") ("ii corinthians" . "/NT/2_Cor")
    ("galatians"      . "/NT/Gal")
    ("ephesians"      . "/NT/Eph")
    ("philippians"    . "/NT/Phl")
    ("colossians"     . "/NT/Col")
    ("1 thessalonians". "/NT/1_Th")  ("i thessalonians" . "/NT/1_Th")
    ("2 thessalonians". "/NT/2_Th")  ("ii thessalonians" . "/NT/2_Th")
    ("1 timothy"      . "/NT/1_Tim") ("i timothy" . "/NT/1_Tim")
    ("2 timothy"      . "/NT/2_Tim") ("ii timothy" . "/NT/2_Tim")
    ("titus"          . "/NT/Tit")
    ("philemon"       . "/NT/Phm")
    ("hebrews"        . "/NT/Heb")
    ("james"          . "/NT/Jas")
    ("1 peter"        . "/NT/1_Pet") ("i peter" . "/NT/1_Pet")
    ("2 peter"        . "/NT/2_Pet") ("ii peter" . "/NT/2_Pet")
    ("1 john"         . "/NT/1_Jn")  ("i john" . "/NT/1_Jn")
    ("2 john"         . "/NT/2_Jn")  ("ii john" . "/NT/2_Jn")
    ("3 john"         . "/NT/3_Jn")  ("iii john" . "/NT/3_Jn")
    ("jude"           . "/NT/Jud")
    ("apocalypse"     . "/NT/Apoc")  ("revelation" . "/NT/Apoc"))
  "Alist mapping lowercase book names and aliases to Knox path suffixes.")



(defconst catholicbible--douay-rheims-books
  '(;; --- Old Testament ---
    ("genesis"        . "/OT/Gen")    ("gen"         . "/OT/Gen")
    ("exodus"         . "/OT/Ex")     ("ex"          . "/OT/Ex")
    ("leviticus"      . "/OT/Lev")    ("lev"         . "/OT/Lev")
    ("numbers"        . "/OT/Num")    ("num"         . "/OT/Num")
    ("deuteronomy"    . "/OT/Dt")     ("deut"        . "/OT/Dt")
    ("joshua"         . "/OT/Jos")    ("josue"       . "/OT/Jos")
    ("judges"         . "/OT/Judg")   ("judg"        . "/OT/Judg")
    ("ruth"           . "/OT/Ru")
    ("1 kings"        . "/OT/1_Kgs")  ("i kings"      . "/OT/1_Kgs")
    ("2 kings"        . "/OT/2_Kgs")  ("ii kings"     . "/OT/2_Kgs")
    ("3 kings"        . "/OT/3_Kgs")  ("iii kings"    . "/OT/3_Kgs")
    ("4 kings"        . "/OT/4_Kgs")  ("iv kings"     . "/OT/4_Kgs")
    ("1 paralipomenon" . "/OT/1_Par") ("i paralipomenon" . "/OT/1_Par")
    ("2 paralipomenon" . "/OT/2_Par") ("ii paralipomenon" . "/OT/2_Par")
    ("1 esdras"       . "/OT/Esd")    ("esdras"       . "/OT/Esd")
    ("2 esdras"       . "/OT/Neh")    ("nehemiah"     . "/OT/Neh")
    ("tobias"         . "/OT/Tob")    ("tobit"        . "/OT/Tob")
    ("judith"         . "/OT/Jdt")
    ("esther"         . "/OT/Est")
    ("job"            . "/OT/Job")
    ("psalms"         . "/OT/Ps")     ("ps"           . "/OT/Ps")
    ("proverbs"       . "/OT/Prov")
    ("ecclesiastes"   . "/OT/Eccl")
    ("canticle of canticles" . "/OT/Cant") ("song of songs" . "/OT/Cant")
    ("wisdom"         . "/OT/Wis")
    ("sirach"         . "/OT/Eccle")  ("ecclesiasticus" . "/OT/Eccle")
    ("isaias"         . "/OT/Isa")    ("isaiah"       . "/OT/Isa")
    ("jeremias"       . "/OT/Jer")    ("jeremiah"     . "/OT/Jer")
    ("lamentations"   . "/OT/Lam")
    ("baruch"         . "/OT/Bar")
    ("ezechiel"       . "/OT/Eze")    ("ezekiel"      . "/OT/Eze")
    ("daniel"         . "/OT/Dan")
    ("osee"           . "/OT/Os")     ("hosea"        . "/OT/Os")
    ("joel"           . "/OT/Jo")
    ("amos"           . "/OT/Am")
    ("abdias"         . "/OT/Abd")    ("obadiah"      . "/OT/Abd")
    ("jonas"          . "/OT/Jon")    ("jonah"        . "/OT/Jon")
    ("micheas"        . "/OT/Mic")    ("micah"        . "/OT/Mic")
    ("nahum"          . "/OT/Nah")
    ("habacuc"        . "/OT/Hab")    ("habakkuk"     . "/OT/Hab")
    ("sophonias"      . "/OT/Sop")    ("zephaniah"    . "/OT/Sop")
    ("aggeus"         . "/OT/Agg")    ("haggai"       . "/OT/Agg")
    ("zacharias"      . "/OT/Zac")    ("zechariah"    . "/OT/Zac")
    ("malachias"      . "/OT/Mal")    ("malachi"      . "/OT/Mal")
    ("1 machabees"    . "/OT/1_Mac")  ("i machabees"  . "/OT/1_Mac")
    ("2 machabees"    . "/OT/2_Mac")  ("ii machabees" . "/OT/2_Mac")

    ;; --- New Testament ---
    ("matthew"        . "/NT/Mat")
    ("mark"           . "/NT/Mk")
    ("luke"           . "/NT/Lk")
    ("john"           . "/NT/Jn")
    ("acts"           . "/NT/Act")    ("acts of apostles" . "/NT/Act")
    ("romans"         . "/NT/Rom")
    ("1 corinthians"  . "/NT/1_Cor")  ("i corinthians" . "/NT/1_Cor")
    ("2 corinthians"  . "/NT/2_Cor")  ("ii corinthians" . "/NT/2_Cor")
    ("galatians"      . "/NT/Gal")
    ("ephesians"      . "/NT/Eph")
    ("philippians"    . "/NT/Phl")
    ("colossians"     . "/NT/Col")
    ("1 thessalonians". "/NT/1_Th")   ("i thessalonians" . "/NT/1_Th")
    ("2 thessalonians". "/NT/2_Th")   ("ii thessalonians" . "/NT/2_Th")
    ("1 timothy"      . "/NT/1_Tim")  ("i timothy" . "/NT/1_Tim")
    ("2 timothy"      . "/NT/2_Tim")  ("ii timothy" . "/NT/2_Tim")
    ("titus"          . "/NT/Tit")
    ("philemon"       . "/NT/Phm")
    ("hebrews"        . "/NT/Heb")
    ("james"          . "/NT/Jas")
    ("1 peter"        . "/NT/1_Pet")  ("i peter" . "/NT/1_Pet")
    ("2 peter"        . "/NT/2_Pet")  ("ii peter" . "/NT/2_Pet")
    ("1 john"         . "/NT/1_Jn")   ("i john" . "/NT/1_Jn")
    ("2 john"         . "/NT/2_Jn")   ("ii john" . "/NT/2_Jn")
    ("3 john"         . "/NT/3_Jn")   ("iii john" . "/NT/3_Jn")
    ("jude"           . "/NT/Jud")
    ("apocalypse"     . "/NT/Apoc")   ("revelation" . "/NT/Apoc"))
  "Alist mapping lowercase book names and aliases to Douay-Rheims path suffixes.")


(defconst catholicbible--vulgate-books
  '(;; --- Old Testament ---
    ("genesis"        . "/OT/Gn")     ("gen"           . "/OT/Gn")
    ("exodus"         . "/OT/Ex")     ("ex"            . "/OT/Ex")
    ("leviticus"      . "/OT/Lv")     ("lev"           . "/OT/Lv")
    ("numbers"        . "/OT/Nm")     ("numeri"        . "/OT/Nm")
    ("deuteronomy"    . "/OT/Dt")     ("deuteronomium" . "/OT/Dt")
    ("josue"          . "/OT/Jos")    ("joshua"        . "/OT/Jos")
    ("judges"         . "/OT/Jdc")    ("judicum"       . "/OT/Jdc")
    ("ruth"           . "/OT/Rt")
    ("1 kings"        . "/OT/1Rg")    ("regum i"       . "/OT/1Rg")
    ("2 kings"        . "/OT/2Rg")    ("regum ii"      . "/OT/2Rg")
    ("3 kings"        . "/OT/3Rg")    ("regum iii"     . "/OT/3Rg")
    ("4 kings"        . "/OT/4Rg")    ("regum iv"      . "/OT/4Rg")
    ("1 paralipomenon" . "/OT/1Par")  ("paralipomenon i" . "/OT/1Par")
    ("2 paralipomenon" . "/OT/2Par")  ("paralipomenon ii" . "/OT/2Par")
    ("1 esdras"       . "/OT/Esr")    ("esdras"        . "/OT/Esr")
    ("2 esdras"       . "/OT/Neh")    ("nehemiah"      . "/OT/Neh")
    ("tobit"          . "/OT/Tob")    ("tobias"        . "/OT/Tob")  ("tobiae" . "/OT/Tob")
    ("judith"         . "/OT/Jdt")
    ("esther"         . "/OT/Est")
    ("job"            . "/OT/Job")
    ("psalms"         . "/OT/Ps")     ("psalmi"        . "/OT/Ps")   ("ps" . "/OT/Ps")
    ("proverbs"       . "/OT/Pr")     ("proverbia"     . "/OT/Pr")
    ("ecclesiastes"   . "/OT/Ecl")
    ("song of songs"  . "/OT/Ct")     ("canticles"     . "/OT/Ct")   ("canticum canticorum" . "/OT/Ct")
    ("wisdom"         . "/OT/Sap")    ("sapientia"     . "/OT/Sap")
    ("sirach"         . "/OT/Sir")    ("ecclesiasticus". "/OT/Sir")
    ("isaiah"         . "/OT/Is")     ("isaias"        . "/OT/Is")
    ("jeremiah"       . "/OT/Jr")     ("jeremias"      . "/OT/Jr")
    ("lamentations"   . "/OT/Lam")    ("lamentationes" . "/OT/Lam")
    ("baruch"         . "/OT/Bar")
    ("ezekiel"        . "/OT/Ez")     ("ezechiel"      . "/OT/Ez")
    ("daniel"         . "/OT/Dn")
    ("hosea"          . "/OT/Os")     ("osee"          . "/OT/Os")
    ("joel"           . "/OT/Joel")
    ("amos"           . "/OT/Am")
    ("obadiah"        . "/OT/Abd")    ("abdias"        . "/OT/Abd")
    ("jonah"          . "/OT/Jon")    ("jonas"         . "/OT/Jon")
    ("micah"          . "/OT/Mch")    ("michaea"       . "/OT/Mch")
    ("nahum"          . "/OT/Nah")
    ("habakkuk"       . "/OT/Hab")    ("habacuc"       . "/OT/Hab")
    ("zephaniah"      . "/OT/Soph")   ("sophonias"     . "/OT/Soph")
    ("haggai"         . "/OT/Agg")    ("aggaeus"       . "/OT/Agg")
    ("zechariah"      . "/OT/Zach")   ("zacharias"     . "/OT/Zach")
    ("malachi"        . "/OT/Mal")    ("malachias"     . "/OT/Mal")
    ("1 maccabees"    . "/OT/1Mcc")   ("machabaeorum i". "/OT/1Mcc")
    ("2 maccabees"    . "/OT/2Mcc")   ("machabaeorum ii". "/OT/2Mcc")

    ;; --- New Testament ---
    ("matthew"        . "/NT/Mt")     ("matthaeum"     . "/NT/Mt")
    ("mark"           . "/NT/Mc")     ("marcum"        . "/NT/Mc")
    ("luke"           . "/NT/Lc")     ("lucam"         . "/NT/Lc")
    ("john"           . "/NT/Jo")     ("joannem"       . "/NT/Jo")
    ("acts"           . "/NT/Act")    ("actus apostolorum" . "/NT/Act")
    ("romans"         . "/NT/Rom")    ("romanos"       . "/NT/Rom")
    ("1 corinthians"  . "/NT/1Cor")   ("i corinthians" . "/NT/1Cor")
    ("2 corinthians"  . "/NT/2Cor")   ("ii corinthians". "/NT/2Cor")
    ("galatians"      . "/NT/Gal")    ("galatas"       . "/NT/Gal")
    ("ephesians"      . "/NT/Eph")    ("ephesios"      . "/NT/Eph")
    ("philippians"    . "/NT/Phlp")   ("philippenses"  . "/NT/Phlp")
    ("colossians"     . "/NT/Col")    ("colossenses"   . "/NT/Col")
    ("1 thessalonians". "/NT/1Thes")  ("i thessalonians". "/NT/1Thes")
    ("2 thessalonians". "/NT/2Thes")  ("ii thessalonians". "/NT/2Thes")
    ("1 timothy"      . "/NT/1Tim")   ("i timothy"     . "/NT/1Tim")
    ("2 timothy"      . "/NT/2Tim")   ("ii timothy"    . "/NT/2Tim")
    ("titus"          . "/NT/Tit")    ("titum"         . "/NT/Tit")
    ("philemon"       . "/NT/Phlm")   ("philemonem"    . "/NT/Phlm")
    ("hebrews"        . "/NT/Hbr")    ("hebraeos"      . "/NT/Hbr")
    ("james"          . "/NT/Jac")    ("jacobi"        . "/NT/Jac")
    ("1 peter"        . "/NT/1Ptr")   ("i peter"       . "/NT/1Ptr")
    ("2 peter"        . "/NT/2Ptr")   ("ii peter"      . "/NT/2Ptr")
    ("1 john"         . "/NT/1Jo")    ("i john"        . "/NT/1Jo")
    ("2 john"         . "/NT/2Jo")    ("ii john"       . "/NT/2Jo")
    ("3 john"         . "/NT/3Jo")    ("iii john"      . "/NT/3Jo")
    ("jude"           . "/NT/Jud")    ("judae"         . "/NT/Jud")
    ("revelation"     . "/NT/Apc")    ("apocalypse"    . "/NT/Apc") ("apocalypsis" . "/NT/Apc"))
  "Alist mapping lowercase book names and aliases to Vulgate path suffixes.")
